In [3]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

In [4]:
# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

In [5]:
# Create DataFrame
df = pd.DataFrame(X, columns=iris.feature_names)
df["target"] = y

print("Dataset Sample:")
print(df.head())

print("\nTarget Classes:")
print(iris.target_names)

# 0 = Setosa
# 1 = Versicolor
# 2 = Virginica

Dataset Sample:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Target Classes:
['setosa' 'versicolor' 'virginica']


In [7]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Display the shapes
print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)
print("Training Labels Shape:", y_train.shape)
print("Testing Labels Shape:", y_test.shape)

Training Data Shape: (120, 4)
Testing Data Shape: (30, 4)
Training Labels Shape: (120,)
Testing Labels Shape: (30,)


In [9]:
from sklearn.preprocessing import StandardScaler

# Feature Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Feature scaling completed successfully!")

Feature scaling completed successfully!


In [11]:
from sklearn.linear_model import LogisticRegression

# Create and train the Logistic Regression model
model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!


In [12]:
y_pred = model.predict(X_test)



In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predict on test data
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:")
print(accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Accuracy:
1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [15]:
sample = X_test[0].reshape(1, -1)
prediction = model.predict(sample)

print("\nSample Prediction:")

if prediction[0] == 0:
    print("Setosa")
elif prediction[0] == 1:
    print("Versicolor")
else:
    print("Virginica")


Sample Prediction:
Versicolor
